Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |v|
    v.memory = 3096
    v.cpus = 2
  end

  config.vm.define "master01" do |master01|
    master01.vm.box = "centos/7"
    master01.vm.hostname = "master01"
    master01.vm.network :private_network, ip: '192.168.42.42'
    master01.hostmanager.aliases = %w(master01)
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "centos/7"
    node01.vm.hostname = "node01"
    node01.vm.network :private_network, ip: '192.168.42.43'
    node01.hostmanager.aliases = %w(node01)
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "centos/7"
    node02.vm.hostname = "node02"
    node02.vm.network :private_network, ip: '192.168.42.44'
    node02.hostmanager.aliases = %w(node02)
  end

end